const cards = [{
  name: 'Nasty Nick',
  series: 1,
  releaseDate: '1985',
  cardNumber: '1',
  AorB: 'A',
}, {
  name: 'Junkfood John',
  series: 1,
  releaseDate: '1985',
  cardNumber: '2',
  AorB: 'A',
}, {
  name: 'Up Chuck',
  series: 1,
  releaseDate: '1985',
  cardNumber: '3',
  AorB: 'A',
}, {
  name: 'Fryin Brian',
  series: 1,
  releaseDate: '1985',
  cardNumber: '4',
  AorB: 'A',
}, {
  name: 'Dead Ted',
  series: 1,
  releaseDate: '1985',
  cardNumber: '5',
  AorB: 'A',
}, {
  name: 'Art Apart',
  series: 1,
  releaseDate: '1985',
  cardNumber: '6',
  AorB: 'A',
}, {
  name: 'Stormy Heather',
  series: 1,
  releaseDate: '1985',
  cardNumber: '7',
  AorB: 'A',
}, {
  name: 'Adam Bomb',
  series: 1,
  releaseDate: '1985',
  cardNumber: '8',
  AorB: 'A',
}, {
  name: 'Boozin Bruce',
  series: 1,
  releaseDate: '1985',
  cardNumber: '9',
  AorB: 'A',
}, {
  name: 'Tee-vee Stevie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '10',
  AorB: 'A',
}, {
  name: 'Itchy Richie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '11',
  AorB: 'A',
}, {
  name: 'Furry Fran',
  series: 1,
  releaseDate: '1985',
  cardNumber: '12',
  AorB: 'A',
}, {
  name: 'Ashcan Andy',
  series: 1,
  releaseDate: '1985',
  cardNumber: '13',
  AorB: 'A',
}, {
  name: 'Potty Scotty',
  series: 1,
  releaseDate: '1985',
  cardNumber: '14',
  AorB: 'A',
}, {
  name: 'Ailin Al',
  series: 1,
  releaseDate: '1985',
  cardNumber: '15',
  AorB: 'A',
}, {
  name: 'Weird Wendy',
  series: 1,
  releaseDate: '1985',
  cardNumber: '16',
  AorB: 'A',
}, {
  name: 'Wacky Jackie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '17',
  AorB: 'A',
}, {
  name: 'Cranky Frankie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '18',
  AorB: 'A',
}, {
  name: 'Corroded Carl',
  series: 1,
  releaseDate: '1985',
  cardNumber: '19',
  AorB: 'A',
}, {
  name: 'Swell Mell',
  series: 1,
  releaseDate: '1985',
  cardNumber: '20',
  AorB: 'A',
}, {
  name: 'Virus Iris',
  series: 1,
  releaseDate: '1985',
  cardNumber: '21',
  AorB: 'A',
}, {
  name: 'Junky Jeff',
  series: 1,
  releaseDate: '1985',
  cardNumber: '22',
  AorB: 'A',
}, {
  name: 'Druppy Dan',
  series: 1,
  releaseDate: '1985',
  cardNumber: '23',
  AorB: 'A',
}, {
  name: 'Nervous Rex',
  series: 1,
  releaseDate: '1985',
  cardNumber: '24',
  AorB: 'A',
}, {
  name: 'Creepy Carol',
  series: 1,
  releaseDate: '1985',
  cardNumber: '25',
  AorB: 'A',
}, {
  name: 'Slobby Robbie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '26',
  AorB: 'A',
}, {
  name: 'Brainy Janie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '27',
  AorB: 'A',
}, {
  name: 'Oozy Suzie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '28',
  AorB: 'A',
}, {
  name: 'Bony Joanie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '29',
  AorB: 'A',
}, {
  name: 'New Wave Dave',
  series: 1,
  releaseDate: '1985',
  cardNumber: '30',
  AorB: 'A',
}, {
  name: 'Run Down Rhoda',
  series: 1,
  releaseDate: '1985',
  cardNumber: '31',
  AorB: 'A',
}, {
  name: 'Frigid Bridget',
  series: 1,
  releaseDate: '1985',
  cardNumber: '32',
  AorB: 'A',
}, {
  name: 'Mad Mike',
  series: 1,
  releaseDate: '1985',
  cardNumber: '33',
  AorB: 'A',
}, {
  name: 'Kim Kong',
  series: 1,
  releaseDate: '1985',
  cardNumber: '34',
  AorB: 'A',
}, {
  name: 'Wrinkly Randy',
  series: 1,
  releaseDate: '1985',
  cardNumber: '35',
  AorB: 'A',
}, {
  name: 'Wrappin Ruth',
  series: 1,
  releaseDate: '1985',
  cardNumber: '36',
  AorB: 'A',
}, {
  name: 'Guillo Tina',
  series: 1,
  releaseDate: '1985',
  cardNumber: '37',
  AorB: 'A',
}, {
  name: 'Slimy Sam',
  series: 1,
  releaseDate: '1985',
  cardNumber: '38',
  AorB: 'A',
}, {
  name: 'Buggy Betty',
  series: 1,
  releaseDate: '1985',
  cardNumber: '39',
  AorB: 'A',
}, {
  name: 'Unstitched Mitch',
  series: 1,
  releaseDate: '1985',
  cardNumber: '40',
  AorB: 'A',
}, {
  name: 'Mean Gene',
  series: 1,
  releaseDate: '1985',
  cardNumber: '41',
  AorB: 'A',
}, {
  name: 'Evil Eddie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '1',
  AorB: 'B',
}, {
  name: 'Ray Decay',
  series: 1,
  releaseDate: '1985',
  cardNumber: '2',
  AorB: 'B',
}, {
  name: 'Heavin Steven',
  series: 1,
  releaseDate: '1985',
  cardNumber: '3',
  AorB: 'B',
}, {
  name: 'Electric Bill',
  series: 1,
  releaseDate: '1985',
  cardNumber: '4',
  AorB: 'B',
}, {
  name: 'Jay Decay',
  series: 1,
  releaseDate: '1985',
  cardNumber: '5',
  AorB: 'B',
}, {
  name: 'Busted Bob',
  series: 1,
  releaseDate: '1985',
  cardNumber: '6',
  AorB: 'B',
}, {
  name: 'April Showers',
  series: 1,
  releaseDate: '1985',
  cardNumber: '7',
  AorB: 'B',
}, {
  name: 'Blasted Billy',
  series: 1,
  releaseDate: '1985',
  cardNumber: '8',
  AorB: 'B',
}, {
  name: 'Drunk Ken',
  series: 1,
  releaseDate: '1985',
  cardNumber: '9',
  AorB: 'B',
}, {
  name: 'Geeky Gary',
  series: 1,
  releaseDate: '1985',
  cardNumber: '10',
  AorB: 'B',
}, {
  name: 'Bugged Bert',
  series: 1,
  releaseDate: '1985',
  cardNumber: '11',
  AorB: 'B',
}, {
  name: 'Hairy Mary',
  series: 1,
  releaseDate: '1985',
  cardNumber: '12',
  AorB: 'B',
}, {
  name: 'Spacey Stacy',
  series: 1,
  releaseDate: '1985',
  cardNumber: '13',
  AorB: 'B',
}, {
  name: 'Jasin Basin',
  series: 1,
  releaseDate: '1985',
  cardNumber: '14',
  AorB: 'B',
}, {
  name: 'Mauled Paul',
  series: 1,
  releaseDate: '1985',
  cardNumber: '15',
  AorB: 'B',
}, {
  name: 'Haggy Maggie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '16',
  AorB: 'B',
}, {
  name: 'Loony Lenny',
  series: 1,
  releaseDate: '1985',
  cardNumber: '17',
  AorB: 'B',
}, {
  name: 'Bad Brad',
  series: 1,
  releaseDate: '1985',
  cardNumber: '18',
  AorB: 'B',
}, {
  name: 'Crater Chris',
  series: 1,
  releaseDate: '1985',
  cardNumber: '19',
  AorB: 'B',
}, {
  name: 'Dressy Jesse',
  series: 1,
  releaseDate: '1985',
  cardNumber: '20',
  AorB: 'B',
}, {
  name: 'Sicky Vicky',
  series: 1,
  releaseDate: '1985',
  cardNumber: '21',
  AorB: 'B',
}, {
  name: 'Stinky Stan',
  series: 1,
  releaseDate: '1985',
  cardNumber: '22',
  AorB: 'B',
}, {
  name: 'Leaky Lou',
  series: 1,
  releaseDate: '1985',
  cardNumber: '23',
  AorB: 'B',
}, {
  name: 'Nerdy Norm',
  series: 1,
  releaseDate: '1985',
  cardNumber: '24',
  AorB: 'B',
}, {
  name: 'Scary Carrie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '25',
  AorB: 'B',
}, {
  name: 'Fat Matt',
  series: 1,
  releaseDate: '1985',
  cardNumber: '26',
  AorB: 'B',
}, {
  name: 'Jenny Genius',
  series: 1,
  releaseDate: '1985',
  cardNumber: '27',
  AorB: 'B',
}, {
  name: 'Meltin Melissa',
  series: 1,
  releaseDate: '1985',
  cardNumber: '28',
  AorB: 'B',
}, {
  name: 'Thin Lynn',
  series: 1,
  releaseDate: '1985',
  cardNumber: '29',
  AorB: 'B',
}, {
  name: 'Graffiti Petey',
  series: 1,
  releaseDate: '1985',
  cardNumber: '30',
  AorB: 'B',
}, {
  name: 'Flat Pat',
  series: 1,
  releaseDate: '1985',
  cardNumber: '31',
  AorB: 'B',
}, {
  name: 'Chilly Millie',
  series: 1,
  releaseDate: '1985',
  cardNumber: '32',
  AorB: 'B',
}, {
  name: 'Savage Stuart',
  series: 1,
  releaseDate: '1985',
  cardNumber: '33',
  AorB: 'B',
}, {
  name: 'Anna Banana',
  series: 1,
  releaseDate: '1985',
  cardNumber: '34',
  AorB: 'B',
}, {
  name: 'Rockin Robert',
  series: 1,
  releaseDate: '1985',
  cardNumber: '35',
  AorB: 'B',
}, {
  name: 'Tommy Tomb',
  series: 1,
  releaseDate: '1985',
  cardNumber: '36',
  AorB: 'B',
}, {
  name: 'Cindy Lopper',
  series: 1,
  releaseDate: '1985',
  cardNumber: '37',
  AorB: 'B',
}, {
  name: 'Lizard Liz',
  series: 1,
  releaseDate: '1985',
  cardNumber: '38',
  AorB: 'B',
}, {
  name: 'Green Jean',
  series: 1,
  releaseDate: '1985',
  cardNumber: '39',
  AorB: 'B',
}, {
  name: 'Damaged Don',
  series: 1,
  releaseDate: '1985',
  cardNumber: '40',
  AorB: 'B',
}, {
  name: 'Joltin Joe',
  series: 1,
  releaseDate: '1985',
  cardNumber: '41',
  AorB: 'B',
}]

module.exports = cards
