const card = [{
  name: 'Nasty Nick',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '1',
  aOrB: 'A',
}, {
  name: 'Junkfood John',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '2',
  aOrB: 'A',
}, {
  name: 'Up Chuck',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '3',
  aOrB: 'A',
}, {
  name: 'Fryin Brian',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '4',
  aOrB: 'A',
}, {
  name: 'Dead Ted',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '5',
  aOrB: 'A',
}, {
  name: 'Art Apart',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '6',
  aOrB: 'A',
}, {
  name: 'Stormy Heather',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '7',
  aOrB: 'A',
}, {
  name: 'Adam Bomb',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '8',
  aOrB: 'A',
}, {
  name: 'Boozin Bruce',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '9',
  aOrB: 'A',
}, {
  name: 'Tee-vee Stevie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '10',
  aOrB: 'A',
}, {
  name: 'Itchy Richie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '11',
  aOrB: 'A',
}, {
  name: 'Furry Fran',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '12',
  aOrB: 'A',
}, {
  name: 'Ashcan Andy',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '13',
  aOrB: 'A',
}, {
  name: 'Potty Scotty',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '14',
  aOrB: 'A',
}, {
  name: 'Ailin Al',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '15',
  aOrB: 'A',
}, {
  name: 'Weird Wendy',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '16',
  aOrB: 'A',
}, {
  name: 'Wacky Jackie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '17',
  aOrB: 'A',
}, {
  name: 'Cranky Frankie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '18',
  aOrB: 'A',
}, {
  name: 'Corroded Carl',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '19',
  aOrB: 'A',
}, {
  name: 'Swell Mell',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '20',
  aOrB: 'A',
}, {
  name: 'Virus Iris',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '21',
  aOrB: 'A',
}, {
  name: 'Junky Jeff',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '22',
  aOrB: 'A',
}, {
  name: 'Druppy Dan',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '23',
  aOrB: 'A',
}, {
  name: 'Nervous Rex',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '24',
  aOrB: 'A',
}, {
  name: 'Creepy Carol',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '25',
  aOrB: 'A',
}, {
  name: 'Slobby Robbie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '26',
  aOrB: 'A',
}, {
  name: 'Brainy Janie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '27',
  aOrB: 'A',
}, {
  name: 'Oozy Suzie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '28',
  aOrB: 'A',
}, {
  name: 'Bony Joanie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '29',
  aOrB: 'A',
}, {
  name: 'New Wave Dave',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '30',
  aOrB: 'A',
}, {
  name: 'Run Down Rhoda',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '31',
  aOrB: 'A',
}, {
  name: 'Frigid Bridget',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '32',
  aOrB: 'A',
}, {
  name: 'Mad Mike',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '33',
  aOrB: 'A',
}, {
  name: 'Kim Kong',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '34',
  aOrB: 'A',
}, {
  name: 'Wrinkly Randy',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '35',
  aOrB: 'A',
}, {
  name: 'Wrappin Ruth',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '36',
  aOrB: 'A',
}, {
  name: 'Guillo Tina',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '37',
  aOrB: 'A',
}, {
  name: 'Slimy Sam',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '38',
  aOrB: 'A',
}, {
  name: 'Buggy Betty',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '39',
  aOrB: 'A',
}, {
  name: 'Unstitched Mitch',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '40',
  aOrB: 'A',
}, {
  name: 'Mean Gene',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '41',
  aOrB: 'A',
}, {
  name: 'Evil Eddie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '1',
  aOrB: 'B',
}, {
  name: 'Ray Decay',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '2',
  aOrB: 'B',
}, {
  name: 'Heavin Steven',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '3',
  aOrB: 'B',
}, {
  name: 'Electric Bill',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '4',
  aOrB: 'B',
}, {
  name: 'Jay Decay',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '5',
  aOrB: 'B',
}, {
  name: 'Busted Bob',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '6',
  aOrB: 'B',
}, {
  name: 'April Showers',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '7',
  aOrB: 'B',
}, {
  name: 'Blasted Billy',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '8',
  aOrB: 'B',
}, {
  name: 'Drunk Ken',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '9',
  aOrB: 'B',
}, {
  name: 'Geeky Gary',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '10',
  aOrB: 'B',
}, {
  name: 'Bugged Bert',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '11',
  aOrB: 'B',
}, {
  name: 'Hairy Mary',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '12',
  aOrB: 'B',
}, {
  name: 'Spacey Stacy',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '13',
  aOrB: 'B',
}, {
  name: 'Jasin Basin',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '14',
  aOrB: 'B',
}, {
  name: 'Mauled Paul',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '15',
  aOrB: 'B',
}, {
  name: 'Haggy Maggie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '16',
  aOrB: 'B',
}, {
  name: 'Loony Lenny',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '17',
  aOrB: 'B',
}, {
  name: 'Bad Brad',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '18',
  aOrB: 'B',
}, {
  name: 'Crater Chris',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '19',
  aOrB: 'B',
}, {
  name: 'Dressy Jesse',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '20',
  aOrB: 'B',
}, {
  name: 'Sicky Vicky',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '21',
  aOrB: 'B',
}, {
  name: 'Stinky Stan',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '22',
  aOrB: 'B',
}, {
  name: 'Leaky Lou',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '23',
  aOrB: 'B',
}, {
  name: 'Nerdy Norm',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '24',
  aOrB: 'B',
}, {
  name: 'Scary Carrie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '25',
  aOrB: 'B',
}, {
  name: 'Fat Matt',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '26',
  aOrB: 'B',
}, {
  name: 'Jenny Genius',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '27',
  aOrB: 'B',
}, {
  name: 'Meltin Melissa',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '28',
  aOrB: 'B',
}, {
  name: 'Thin Lynn',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '29',
  aOrB: 'B',
}, {
  name: 'Graffiti Petey',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '30',
  aOrB: 'B',
}, {
  name: 'Flat Pat',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '31',
  aOrB: 'B',
}, {
  name: 'Chilly Millie',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '32',
  aOrB: 'B',
}, {
  name: 'Savage Stuart',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '33',
  aOrB: 'B',
}, {
  name: 'Anna Banana',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '34',
  aOrB: 'B',
}, {
  name: 'Rockin Robert',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '35',
  aOrB: 'B',
}, {
  name: 'Tommy Tomb',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '36',
  aOrB: 'B',
}, {
  name: 'Cindy Lopper',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '37',
  aOrB: 'B',
}, {
  name: 'Lizard Liz',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '38',
  aOrB: 'B',
}, {
  name: 'Green Jean',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '39',
  aOrB: 'B',
}, {
  name: 'Damaged Don',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '40',
  aOrB: 'B',
}, {
  name: 'Joltin Joe',
  Series: 1,
  releaseDate: '1985',
  cardNumber: '41',
  aOrB: 'B',
}]

module.exports = card
